import {env} from "cloudflare:workers";
import {and,asc,eq,gte,inArray,isNull,lte} from "drizzle-orm";
import {getDb} from "../../../db";
import {timelineRecords} from "../../../db/schema";

type RecordInput={tripId?:number|null;entryDate:string;recordType:"visit"|"activity";title:string;note?:string;startTime:string;endTime?:string;transportType?:string;originalTransportType?:string;distanceMeters?:number;startPlace?:string;endPlace?:string;startLat?:string;startLng?:string;endLat?:string;endLng?:string;sourceId?:string};
const clean=(r:RecordInput)=>({...r,tripId:r.tripId||null,entryDate:r.startTime.slice(0,10)||r.entryDate,title:r.title.trim(),note:r.note?.trim()||"",endTime:r.endTime||null,transportType:r.transportType||null,originalTransportType:r.originalTransportType||null,distanceMeters:Number.isFinite(Number(r.distanceMeters))?Math.max(0,Math.round(Number(r.distanceMeters))):null,startPlace:r.startPlace?.trim()||null,endPlace:r.endPlace?.trim()||null,startLat:r.startLat||null,startLng:r.startLng||null,endLat:r.endLat||null,endLng:r.endLng||null,sourceId:r.sourceId||null});
const insertColumns=["trip_id","entry_date","record_type","title","note","start_time","end_time","transport_type","original_transport_type","distance_meters","start_place","end_place","start_lat","start_lng","end_lat","end_lng","source_id"];
const recordValues=(r:ReturnType<typeof clean>)=>[r.tripId,r.entryDate,r.recordType,r.title,r.note,r.startTime,r.endTime,r.transportType,r.originalTransportType,r.distanceMeters,r.startPlace,r.endPlace,r.startLat,r.startLng,r.endLat,r.endLng,r.sourceId];
export async function GET(request:Request){const u=new URL(request.url),tripId=Number(u.searchParams.get("tripId")),from=u.searchParams.get("from")||"0000-01-01",to=u.searchParams.get("to")||"9999-12-31";try{const where=tripId?eq(timelineRecords.tripId,tripId):and(isNull(timelineRecords.tripId),gte(timelineRecords.entryDate,from),lte(timelineRecords.entryDate,to));return Response.json({records:await getDb().select().from(timelineRecords).where(where).orderBy(asc(timelineRecords.startTime)).limit(1000)})}catch{return Response.json({records:[]})}}
export async function POST(request:Request){try{const p=await request.json() as {records?:RecordInput[];tripId?:number|null},rows=(p.records||[]).filter(r=>r.startTime&&r.title&&(r.recordType==="visit"||r.recordType==="activity")).slice(0,1000).map(r=>clean({...r,tripId:p.tripId??r.tripId}));if(!rows.length)return Response.json({error:"저장할 기록이 없습니다."},{status:400});const statements=[];for(let i=0;i<rows.length;i+=5){const chunk=rows.slice(i,i+5),values=chunk.flatMap(recordValues),groups=chunk.map(()=>`(${insertColumns.map(()=>"?").join(",")})`).join(",");statements.push(env.DB.prepare(`INSERT INTO timeline_records (${insertColumns.join(",")}) VALUES ${groups}`).bind(...values))}await env.DB.batch(statements);return Response.json({count:rows.length},{status:201})}catch(error){console.error("timeline record save failed",error);return Response.json({error:"기록을 저장하지 못했습니다."},{status:500})}}
export async function PUT(request:Request){try{const p=await request.json() as RecordInput&{id:number};if(!p.id||!p.title?.trim()||!p.startTime)return Response.json({error:"필수 내용을 입력해주세요."},{status:400});const[record]=await getDb().update(timelineRecords).set(clean(p)).where(eq(timelineRecords.id,p.id)).returning();return record?Response.json({record}):Response.json({error:"기록을 찾지 못했습니다."},{status:404})}catch{return Response.json({error:"기록을 수정하지 못했습니다."},{status:500})}}
export async function DELETE(request:Request){try{const id=Number(new URL(request.url).searchParams.get("id"));if(!id)return Response.json({error:"기록을 선택해주세요."},{status:400});await getDb().delete(timelineRecords).where(eq(timelineRecords.id,id));return Response.json({ok:true})}catch{return Response.json({error:"기록을 삭제하지 못했습니다."},{status:500})}}

export async function PATCH(request:Request){try{const p=await request.json() as {action:string;ids?:number[];record?:RecordInput;token?:string};if(p.action==="merge"){const ids=[...new Set((p.ids||[]).map(Number).filter(Boolean))];if(ids.length<2||!p.record)return Response.json({error:"합칠 이동 기록을 2개 이상 선택해주세요."},{status:400});const originals=await getDb().select().from(timelineRecords).where(inArray(timelineRecords.id,ids)).orderBy(asc(timelineRecords.startTime));if(originals.length!==ids.length||originals.some(r=>r.recordType!=="activity"))return Response.json({error:"선택한 이동 기록을 확인해주세요."},{status:400});const token=crypto.randomUUID(),record=clean({...p.record,recordType:"activity",sourceId:`merge:${token}`});const columns=["trip_id","entry_date","record_type","title","note","start_time","end_time","transport_type","original_transport_type","distance_meters","start_place","end_place","start_lat","start_lng","end_lat","end_lng","source_id"],values=[record.tripId,record.entryDate,record.recordType,record.title,record.note,record.startTime,record.endTime,record.transportType,record.originalTransportType,record.distanceMeters,record.startPlace,record.endPlace,record.startLat,record.startLng,record.endLat,record.endLng,record.sourceId];await env.DB.batch([env.DB.prepare(`INSERT INTO timeline_records (${columns.join(",")}) VALUES (${columns.map(()=>"?").join(",")})`).bind(...values),env.DB.prepare("INSERT INTO timeline_merge_history (merge_token, original_records) VALUES (?, ?)").bind(token,JSON.stringify(originals)),env.DB.prepare(`DELETE FROM timeline_records WHERE id IN (${ids.map(()=>"?").join(",")})`).bind(...ids)]);const merged=await getDb().select().from(timelineRecords).where(eq(timelineRecords.sourceId,`merge:${token}`)).limit(1);return Response.json({record:merged[0],token})}
if(p.action==="undo"&&p.token){const history=await env.DB.prepare("SELECT original_records, undone_at FROM timeline_merge_history WHERE merge_token = ?").bind(p.token).first<{original_records:string;undone_at:string|null}>();if(!history||history.undone_at)return Response.json({error:"이미 되돌렸거나 되돌릴 기록이 없습니다."},{status:400});const originals=JSON.parse(history.original_records) as any[],statements=originals.map(r=>env.DB.prepare("INSERT INTO timeline_records (id,trip_id,entry_date,record_type,title,note,start_time,end_time,transport_type,original_transport_type,distance_meters,start_place,end_place,start_lat,start_lng,end_lat,end_lng,source_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(r.id,r.tripId,r.entryDate,r.recordType,r.title,r.note,r.startTime,r.endTime,r.transportType,r.originalTransportType,r.distanceMeters,r.startPlace,r.endPlace,r.startLat,r.startLng,r.endLat,r.endLng,r.sourceId,r.createdAt));statements.push(env.DB.prepare("DELETE FROM timeline_records WHERE source_id = ?").bind(`merge:${p.token}`),env.DB.prepare("UPDATE timeline_merge_history SET undone_at = CURRENT_TIMESTAMP WHERE merge_token = ?").bind(p.token));await env.DB.batch(statements);return Response.json({records:originals})}return Response.json({error:"올바른 작업이 아닙니다."},{status:400})}catch{return Response.json({error:"안전하게 처리하지 못해 기존 기록을 그대로 두었습니다."},{status:500})}}
