export type ImportedTimelineRecord={recordType:"visit"|"activity";title:string;startTime:string;endTime:string;transportType?:string;originalTransportType?:string;distanceMeters?:number;startPlace?:string;endPlace?:string;startLat?:string;startLng?:string;endLat?:string;endLng?:string;sourceId?:string};

const transportNames:Record<string,string>={in_passenger_vehicle:"자동차",inpassengervehicle:"자동차",passenger_vehicle:"자동차",walking:"도보",on_foot:"도보",bus:"버스",in_bus:"버스",train:"기차",in_train:"기차",cycling:"자전거",on_bicycle:"자전거",subway:"지하철",in_subway:"지하철"};
export function koreanTransport(value:unknown){const raw=String(value||"").trim();if(!raw)return "알 수 없음";const key=raw.toLowerCase().replace(/[ -]+/g,"_");return transportNames[key]||raw;}
function text(value:any):string{if(typeof value==="string")return value;if(!value||typeof value!=="object")return "";return text(value.name)||text(value.text)||text(value.localizedText)||text(value.address)}
function time(value:any):string{if(typeof value==="string")return value;if(typeof value==="number")return new Date(value>1e12?value:value*1000).toISOString();if(!value||typeof value!=="object")return "";return time(value.timestamp)||time(value.dateTime)||time(value.time)||time(value.startTimestamp)}
function point(value:any):{lat:string;lng:string;label:string}{if(!value)return{lat:"",lng:"",label:""};const raw=typeof value==="string"?value:(value.placeLocation||value.latLng||value.geo||value.coordinates||"");if(typeof raw==="string"&&raw){const clean=raw.replace(/^geo:/,"").split("?")[0],parts=clean.split(",").map(v=>v.trim());if(parts.length===2&&parts.every(v=>Number.isFinite(Number(v))))return{lat:parts[0],lng:parts[1],label:`위치 ${Number(parts[0]).toFixed(5)}, ${Number(parts[1]).toFixed(5)}`}}
const lat=value.latitudeE7!=null?Number(value.latitudeE7)/1e7:value.latitude,lng=value.longitudeE7!=null?Number(value.longitudeE7)/1e7:(value.longitude??value.lng);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat:String(lat),lng:String(lng),label:`위치 ${Number(lat).toFixed(5)}, ${Number(lng).toFixed(5)}`}:{lat:"",lng:"",label:text(value)} }
export function parseTimeline(raw:any):ImportedTimelineRecord[]{const segments=raw?.semanticSegments||raw?.timelineObjects||raw?.timeline?.semanticSegments||raw?.timeline?.timelineObjects||raw;const result:ImportedTimelineRecord[]=[];(Array.isArray(segments)?segments:[]).forEach((s:any,i:number)=>{
const activity=s.activity||s.activitySegment;if(activity){const a=activity,candidate=a.topCandidate||a,from=point(a.start||a.startLocation||s.startLocation),to=point(a.end||a.endLocation||s.endLocation),original=text(candidate.type)||String(candidate.type||a.activityType||""),start=time(s.startTime)||time(a.startTime)||time(s.duration?.startTimestamp)||time(a.duration?.startTimestamp),end=time(s.endTime)||time(a.endTime)||time(s.duration?.endTimestamp)||time(a.duration?.endTimestamp);if(!start)return;const meters=a.distanceMeters??a.distance;result.push({recordType:"activity",title:koreanTransport(original),transportType:koreanTransport(original),originalTransportType:original,distanceMeters:Number.isFinite(Number(meters))?Math.round(Number(meters)):undefined,startTime:start,endTime:end,startPlace:text(a.start)||text(a.startLocation)||from.label||"출발지 입력 필요",endPlace:text(a.end)||text(a.endLocation)||to.label||"도착지 입력 필요",startLat:from.lat,startLng:from.lng,endLat:to.lat,endLng:to.lng,sourceId:String(s.timelinePath?.source||i)});return}
const visit=s.visit||s.placeVisit||(s.location||s.topCandidate?s:null);if(!visit)return;const start=time(s.startTime)||time(visit.startTime)||time(s.duration?.startTimestamp)||time(visit.duration?.startTimestamp),end=time(s.endTime)||time(visit.endTime)||time(s.duration?.endTimestamp)||time(visit.duration?.endTimestamp);if(!start)return;const candidate=visit.topCandidate||visit.location||visit,where=point(candidate.placeLocation||candidate.location||candidate),semantic=String(candidate.semanticType||"").toLowerCase(),name=text(candidate.placeName)||text(candidate.name)||text(candidate.address)||text(visit.location?.name)||(semantic.includes("home")?"집":semantic.includes("work")?"직장":"");if(name||where.label||candidate.placeID||candidate.placeId)result.push({recordType:"visit",title:name||"장소명 입력 필요",startTime:start,endTime:end,startPlace:name||where.label||"장소명 입력 필요",startLat:where.lat,startLng:where.lng,sourceId:String(candidate.placeID||candidate.placeId||i)})});return result.sort((a,b)=>a.startTime.localeCompare(b.startTime))}
